sonarqube-check:
  image: gradle:8.13-jdk17
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - cd backend
    - chmod +x ./gradlew    # 실행 권한 부여
    - ./gradlew sonar -Dsonar.projectKey=S12P31S105 -Dsonar.host.url="$SONAR_HOST_URL" -Dsonar.login="$SONAR_TOKEN"
  allow_failure: true
  only:
    - dev-be
  tags:
    - scanner
    - sonarqube