version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-blue
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=dev
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - SERVER_DOMAIN=${SERVER_DOMAIN}
      - FASTAPI_URL=${FASTAPI_URL}
      - AES_SECRET_KEY=${AES_SECRET_KEY}
      - MATTERMOST_WEBHOOK=${MATTERMOST_WEBHOOK}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - FFPROBE_PATH=${FFPROBE_PATH}
      - FFMPEG_PATH=${FFMPEG_PATH}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - gradle-cache:/home/gradle/.gradle
    networks:
      - blue-network

  frontend:
    build: ./frontend
    container_name: frontend-blue
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - ai
    volumes:
      - npm-cache:/root/.npm
    networks:
      - blue-network

  ai:
    build: ./ai
    container_name: ai-blue
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DART_API_KEY=${DART_API_KEY}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - GMS_KEY=${GMS_KEY}
      - GMS_API_BASE=${GMS_API_BASE}
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - pip-cache:/root/.cache/pip
    networks:
      - blue-network

  # MySQL은 공유 가능하도록 shared 네트워크에 연결
  mysql:
    image: mysql:8.0.4
    container_name: mysql-shared
    healthcheck:
      test: ["CMD", "mysql", "--user=${MYSQL_USER}", "--password=${MYSQL_PASSWORD}", "-e", "SELECT 1"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 15s
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=hellojob
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Seoul
    ports:
      - "23309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-time-zone='+09:00'
    networks:
      - blue-network
      - green-network
      - shared-network

networks:
  blue-network:
    name: blue-network
  shared-network:
    name: shared-network

volumes:
  mysql_data:
  npm-cache:
  gradle-cache:
  pip-cache: