version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-blue
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=dev
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - FRONTEND_URL=${FRONTEND_URL}
      - SERVER_DOMAIN=${SERVER_DOMAIN}
      - FASTAPI_URL=${FASTAPI_URL}
      - AES_SECRET_KEY=${AES_SECRET_KEY}
      - MATTERMOST_WEBHOOK=${MATTERMOST_WEBHOOK}
      - OPENAI_API_URL=${OPENAI_API_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - FFPROBE_PATH=${FFPROBE_PATH}
      - FFMPEG_PATH=${FFMPEG_PATH}
    volumes:
      - gradle-cache:/home/gradle/.gradle
    networks:
      - blue-network
      - shared-network

  frontend:
    build: ./frontend
    container_name: frontend-blue
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - ai
    volumes:
      - npm-cache:/root/.npm
    networks:
      - blue-network
      - shared-network

  ai:
    build: ./ai
    container_name: ai-blue
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DART_API_KEY=${DART_API_KEY}
      - NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
      - NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
      - GMS_KEY=${GMS_KEY}
      - GMS_API_BASE=${GMS_API_BASE}
    volumes:
      - pip-cache:/root/.cache/pip
    networks:
      - blue-network
      - shared-network

networks:
  blue-network:
    name: blue-network
  shared-network:
    name: shared-network
    external: true  # 외부에 정의된 네트워크 사용

volumes:
  gradle-cache:
  npm-cache:
  pip-cache:
  mysql_data:
    external: true