services:
  hellojob-app:
    image: hellojob-image # Dockerfile 빌드 시 사용할 이미지 이름
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # 호스트의 .env 파일을 컨테이너 내부로 마운트
      - ./.env:/root/hellojob/.env 
      # 호스트의 소스 코드를 컨테이너 내부로 마운트
      - ./main.py:/root/hellojob/main.py
      - ./app:/root/hellojob/app
    environment:
      - ENV_FILE=/root/hellojob/.env # 컨테이너 내부에서 .env 파일 경로를 참조할 환경 변수 설정`