spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jackson:
    time-zone: Asia/Seoul

  profiles:
    active:
      - local
    group:
      local:
        - oauth
        - db-local
        - mattermost-local
        - s3-local
        #        - cloud
      dev:
        - oauth
        - db-dev
        - mattermost-dev
        #        - cloud
    include: db, oauth, mattermost, s3

logging:
  level:
    org.springframework.security: DEBUG
    com.ssafy: DEBUG