spring:
  profiles:
    active:
      - local
    group:
      local:
        - oauth
        - db-local
        - mattermost-local
        #        - cloud
      dev:
        - oauth
        - db-dev
        - mattermost-dev
        #        - cloud
    include: db, oauth, mattermost

logging:
  level:
    org.springframework.security: DEBUG
    com.ssafy: DEBUG
