
---
spring:
  config:
    activate:
      on-profile: "db-local"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:23306/freedom?useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: ssafy

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul

---
spring:
  config:
    activate:
      on-profile: "db-dev"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    # HikariCP 풀 설정
    hikari:
      minimum-idle: 10            # 유휴 상태로 유지할 커넥션의 최소 수 - 기본값과 동일
      maximum-pool-size: 30       # 최대 커넥션 수(풀의 크기) - 10(기본값) > 30으로 증가
      idle-timeout: 30000         # 유휴 상태 커넥션을 제거하기까지 대기하는 시간 - 10분( > 3초
      max-lifetime: 600000        # 커넥션의 최대 생존 시간 - 30분 > 10분
      connection-timeout: 30000   # 커넥션 풀에서 커넥션을 얻기 위해 기다리는 최대 시간 - 30초(기본값)


  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
